name: "Polyfills"
exports: "polyfills.js"
web: "[mootools.net](http://mootools.net)"
description: "MooTools, The JavaScript framework"
license: "[MIT License](http://mootools.net/license.txt)"
copyright: "&copy; [MooTools](http://mootools.net)"
authors: "[MooTools Development Team](http://mootools.net/developers)"
sources:
  - "Array/Array.isArray.js"
  - "Array/Array.prototype.every.js"
  - "Array/Array.prototype.filter.js"
  - "Array/Array.prototype.forEach.js"
  - "Array/Array.prototype.indexOf.js"
  - "Array/Array.prototype.lastIndexOf.js"
  - "Array/Array.prototype.map.js"
  - "Array/Array.prototype.reduce.js"
  - "Array/Array.prototype.shuffle.js"
  - "Array/Array.prototype.some.js"
  - "Date/Date.now.js"
  - "Element/Element.placeholder.js"
  - "Event/Event.js"
  - "Function/Function.prototype.bind.js"
  - "Function/Function.prototype.construct.js"
  - "Number/Number.prototype.parity.js"
  - "Object/Object.create.js"
  - "Object/Object.defineProperties.js"
  - "Object/Object.extend.js"
  - "Object/Object.forEach.js"
  - "Object/Object.getOwnPropertyNames.js"
  - "Object/Object.getPrototypeOf.js"
  - "Object/Object.keys.js"
  - "Object/Object.toQueryString.js"
  - "String/String.prototype.trim.js"
